[build]
  command = "corepack enable && pnpm -w install && pnpm --filter admin build"
  publish = "apps/admin/dist"

[dev]
  command = "pnpm --filter admin dev"
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"        # prevent Netlify from running npm ci
  NETLIFY_USE_PNPM = "true"      # extra hint for pnpm
